### ISSUE TITLE
Latest ionicons version?

### ISSUE THREAD

**Issue by mesqueeb** [andrewsardone/ionicons-sketch#1]
Is this the latest version of ionicons?

**Comment by andrewsardone** [comment]
@mesqueeb, no, it's a version of Ionicons from back in 2015. Upgrading would be nice.

Let's keep this thread open as an issue filed to upgrade. I don't imagine I'll get to it soon, but PRs are welcome!

**Comment by andrewsardone** [comment]
I believe this was resolved with https://github.com/andrewsardone/ionicons-sketch/pull/2, so I'm closing this issue. Please reopen if I'm mistaken. Thanks!

**Comment by mesqueeb** [comment]
Nice!!
